import streamlit as st
import pandas as pd

# --- 1. CONFIGURATION ---
st.set_page_config(page_title="Bid Plausibility Checker PoC", layout="wide")
st.title("Contractor Bid Plausibility Checker")
st.markdown("Compare a contractor's bid against the calculated minimum material and labor cost baseline to detect potential anomalies, underpayments ('wage dumping'), or unrealistic pricing.")

# --- 2. DATA LOADING ---
@st.cache_data
def load_data():
    try:
        # Paths to the cleaned datasets generated by the preprocessing scripts
        materials_df = pd.read_csv('data/clean/clean_materials_final.csv')
        labor_df = pd.read_csv('data/clean/clean_tariflöhne.csv') 
        return materials_df, labor_df
    except FileNotFoundError:
        st.error("Error: Could not locate the required data files. Please ensure the preprocessing scripts have been executed and files exist in 'data/clean/'.")
        return None, None

materials, labor = load_data()

if materials is not None and labor is not None:
    
    # --- 3. CONTRACTOR BID INPUT ---
    st.header("1. Contractor Bid Summary")
    total_bid = st.number_input("Total Contractor Bid Amount (€)", min_value=0.0, step=100.0)

    st.divider()

    # --- 4. USER INTERFACE (DYNAMIC BILL OF MATERIALS & LABOR) ---
    st.header("2. Specification (Bill of Materials & Labor)")
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Material List")
        st.write("Add required materials and quantities:")
        
        # Initialize layout with the first item from the dataset as default row
        initial_mat_df = pd.DataFrame({
            "Item_Name": [materials['Item_Name'].iloc[0]], 
            "Quantity": [1.0]
        })
        
        # Professional dynamic data editor for materials
        edited_mat = st.data_editor(
            initial_mat_df,
            column_config={
                "Item_Name": st.column_config.SelectboxColumn("Material Item", options=materials['Item_Name'].tolist(), required=True),
                "Quantity": st.column_config.NumberColumn("Quantity (Units/Meters)", min_value=0.0, required=True)
            },
            num_rows="dynamic",
            key="material_editor"
        )

    with col2:
        st.subheader("Labor Allocation")
        st.write("Add required wage groups and estimated working hours:")
        
        # Initialize layout with the first item from the dataset as default row
        initial_lab_df = pd.DataFrame({
            "Lohngruppe": [labor['Lohngruppe'].iloc[0]], 
            "Hours": [1.0]
        })
        
        # Professional dynamic data editor for labor
        edited_lab = st.data_editor(
            initial_lab_df,
            column_config={
                "Lohngruppe": st.column_config.SelectboxColumn("Wage Group (Lohngruppe)", options=labor['Lohngruppe'].tolist(), required=True),
                "Hours": st.column_config.NumberColumn("Working Hours", min_value=0.0, required=True)
            },
            num_rows="dynamic",
            key="labor_editor"
        )

    st.divider()

    # --- 5. CALCULATION CORE ---
    st.header("3. Plausibility Evaluation")
    
    if st.button("Analyze Bid", type="primary"):
        # Calculate total material costs
        total_mat_cost = 0.0
        for index, row in edited_mat.iterrows():
            mat_name = row["Item_Name"]
            qty = row["Quantity"]
            # Extract the correct price from the structured database
            price = materials.loc[materials['Item_Name'] == mat_name, 'Price'].values[0]
            total_mat_cost += price * qty

        # Calculate total labor costs
        total_lab_cost = 0.0
        for index, row in edited_lab.iterrows():
            lab_group = row["Lohngruppe"]
            hours = row["Hours"]
            # Extract the statutory minimum wage from the structured database
            hourly_rate = labor.loc[labor['Lohngruppe'] == lab_group, 'GTL_Price'].values[0]
            total_lab_cost += hourly_rate * hours

        baseline_cost = total_mat_cost + total_lab_cost

        # Display granular calculation results
        st.write("### Baseline Calculation Summary")
        st.write(f"- **Total Material Cost:** €{total_mat_cost:.2f}")
        st.write(f"- **Total Labor Cost:** €{total_lab_cost:.2f}")
        st.write(f"- **Absolute Minimum Required Cost:** **€{baseline_cost:.2f}**")

        st.divider()

        # --- 6. DECISION RULE & COMPLIANCE OUTPUT ---
        if total_bid == 0:
            st.warning("Please enter a total contractor bid amount above €0.00 to execute the plausibility check.")
        elif total_bid < baseline_cost:
            st.error(f"RED FLAG: The contractor's bid (€{total_bid:.2f}) is lower than the calculated absolute minimum cost baseline (€{baseline_cost:.2f}). This indicates a significant risk of non-compliance, underpayment ('wage dumping'), substandard material selection, or an underlying pricing error by the contractor.")
        else:
            st.success(f"PLAUSIBLE: The contractor's bid (€{total_bid:.2f}) meets or exceeds the calculated absolute minimum cost baseline (€{baseline_cost:.2f}). This bid is economically realistic and compliant with the minimum cost standards.")